# Change these first
owner: SetCr4 # Your GitHub organization or username, where this repository lives
repo: cr4-upptime # The name of this repository

sites:
  - name: Mainpage
    url: https://cr4.live
  - name: Selfhosted Pi
    url: https://sys.pi.cr4.live
  - name: HypeParty
    url: https://hypeparty.cr4.live

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cr4.live
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/SetCr4/cr4-upptime/master/assets/Status.png
  name: Cr4 Statuspage
  introTitle: "Statuspage for Cr4's services. Made by **Upptime**, powered entirely by GitHub."
  introMessage: Here you can see if any service is currently down, why they are down and if there was a maintenance scheduled prior to the downtime. Check the discord for further updates and news.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Discord
      href: https://discord.gg/ccTNyCDUs9

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
