# Change these first
owner: SetCr4 # Your GitHub organization or username, where this repository lives
repo: cr4-upptime # The name of this repository

sites:
  - name: Main Server (HS VM)
    check: "tcp-ping"
    url: cr4.live
    port: 35022
  - name: Home Server (Raspi)
    check: "tcp-ping"
    url: pi.cr4.live
    port: 42069
  - name: Moepi Server
    check: "tcp-ping"
    url: 157.90.112.60
    port: 22
  - name: HypeParty
    url: https://hypeparty.cr4.live

status-website:
  theme: night
  cname: status.cr4.live
  logoUrl: https://raw.githubusercontent.com/SetCr4/cr4-upptime/master/assets/Status.png
  favicon: https://raw.githubusercontent.com/SetCr4/cr4-upptime/master/assets/Status.png
  name: Cr4 Statuspage
  introTitle: "Statuspage for Cr4's services. Made by **Upptime**, powered entirely by GitHub."
  introMessage: Here you can see if any service is currently down, why they are down and if there was a maintenance scheduled prior to the downtime. Check the discord for further updates and news.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Support Discord
      href: https://discord.gg/ccTNyCDUs9
